type_adv = {
    'normal': {
        'normal':10,
        'fire':10,
        'water':10,
        'electric':10,
        'grass':10,
        'ice':10,
        'fighting':10,
        'poison':10,
        'ground':10,
        'flying':10,
        'psychic':10,
        'bug':10,
        'rock':2.5,
        'ghost':0,
        'dragon':10,
        'dark':10,
        'steel':2.5,
        'fairy':10,
    },
    'fire': {
        'normal':10,
        'fire':2.5,
        'water':2.5,
        'electric':10,
        'grass':20,
        'ice':20,
        'fighting':10,
        'poison':10,
        'ground':10,
        'flying':10,
        'psychic':10,
        'bug':20,
        'rock':2.5,
        'ghost':0,
        'dragon':10,
        'dark':10,
        'steel':2.5,
        'fairy':10,
    },
    'water': {
        'normal':10,
        'fire':20,
        'water':2.5,
        'electric':10,
        'grass':2.5,
        'ice':10,
        'fighting':10,
        'poison':10,
        'ground':20,
        'flying':10,
        'psychic':10,
        'bug':10,
        'rock':20,
        'ghost':10,
        'dragon':2.5,
        'dark':10,
        'steel':10,
        'fairy':10,
    },
    'electric': {
        'normal':10,
        'fire':10,
        'water':20,
        'electric':2.5,
        'grass':2.5,
        'ice':10,
        'fighting':10,
        'poison':10,
        'ground':0,
        'flying':20,
        'psychic':10,
        'bug':10,
        'rock':10,
        'ghost':10,
        'dragon':2.5,
        'dark':10,
        'steel':10,
        'fairy':10,
    },
    'grass': {
        'normal':10,
        'fire':2.5,
        'water':20,
        'electric':10,
        'grass':2.5,
        'ice':10,
        'fighting':10,
        'poison':2.5,
        'ground':20,
        'flying':2.5,
        'psychic':0,
        'bug':2.5,
        'rock':20,
        'ghost':10,
        'dragon':2.5,
        'dark':10,
        'steel':2.5,
        'fairy':10,
    },
    'ice': {
        'normal':10,
        'fire':2.5,
        'water':2.5,
        'electric':10,
        'grass':20,
        'ice':2.5,
        'fighting':10,
        'poison':10,
        'ground':20,
        'flying':20,
        'psychic':10,
        'bug':10,
        'rock':10,
        'ghost':10,
        'dragon':20,
        'dark':10,
        'steel':2.5,
        'fairy':10,
    },
    'fighting': {
        'normal':20,
        'fire':10,
        'water':10,
        'electric':10,
        'grass':10,
        'ice':20,
        'fighting':0,
        'poison':2.5,
        'ground':0,
        'flying':2.5,
        'psychic':2.5,
        'bug':2.5,
        'rock':20,
        'ghost':0,
        'dragon':10,
        'dark':20,
        'steel':20,
        'fairy':2.5,
    },
    'poison': {
        'normal':10,
        'fire':10,
        'water':10,
        'electric':10,
        'grass':20,
        'ice':10,
        'fighting':10,
        'poison':2.5,
        'ground':2.5,
        'flying':10,
        'psychic':10,
        'bug':10,
        'rock':2.5,
        'ghost':2.5,
        'dragon':10,
        'dark':10,
        'steel':0,
        'fairy':20,
    },
    'ground': {
        'normal':10,
        'fire':20,
        'water':10,
        'electric':20,
        'grass':2.5,
        'ice':10,
        'fighting':10,
        'poison':20,
        'ground':10,
        'flying':0,
        'psychic':10,
        'bug':2.5,
        'rock':20,
        'ghost':10,
        'dragon':10,
        'dark':10,
        'steel':20,
        'fairy':10,
    },
    'flying': {
        'normal':10,
        'fire':10,
        'water':10,
        'electric':2.5,
        'grass':20,
        'ice':10,
        'fighting':20,
        'poison':10,
        'ground':10,
        'flying':10,
        'psychic':10,
        'bug':20,
        'rock':2.5,
        'ghost':10,
        'dragon':10,
        'dark':10,
        'steel':2.5,
        'fairy':10,
    },
    'psychic': {
        'normal':10,
        'fire':10,
        'water':10,
        'electric':10,
        'grass':10,
        'ice':10,
        'fighting':20,
        'poison':20,
        'ground':10,
        'flying':10,
        'psychic':2.5,
        'bug':10,
        'rock':10,
        'ghost':10,
        'dragon':10,
        'dark':0,
        'steel':2.5,
        'fairy':10,
    },
    'bug': {
        'normal':10,
        'fire':2.5,
        'water':10,
        'electric':10,
        'grass':20,
        'ice':10,
        'fighting':2.5,
        'poison':2.5,
        'ground':10,
        'flying':2.5,
        'psychic':20,
        'bug':10,
        'rock':10,
        'ghost':2.5,
        'dragon':10,
        'dark':20,
        'steel':2.5,
        'fairy':2.5,
    },
    'rock': {
        'normal':10,
        'fire':20,
        'water':10,
        'electric':10,
        'grass':10,
        'ice':20,
        'fighting':2.5,
        'poison':10,
        'ground':2.5,
        'flying':20,
        'psychic':10,
        'bug':20,
        'rock':10,
        'ghost':10,
        'dragon':10,
        'dark':10,
        'steel':2.5,
        'fairy':10,
    },
    'ghost': {
        'normal':0,
        'fire':10,
        'water':10,
        'electric':10,
        'grass':10,
        'ice':10,
        'fighting':10,
        'poison':10,
        'ground':10,
        'flying':10,
        'psychic':20,
        'bug':10,
        'rock':10,
        'ghost':20,
        'dragon':10,
        'dark':2.5,
        'steel':10,
        'fairy':10,
    },
    'dragon': {
        'normal':10,
        'fire':10,
        'water':10,
        'electric':10,
        'grass':10,
        'ice':10,
        'fighting':10,
        'poison':10,
        'ground':10,
        'flying':10,
        'psychic':10,
        'bug':10,
        'rock':10,
        'ghost':10,
        'dragon':20,
        'dark':10,
        'steel':2.5,
        'fairy':0,
    },
    'dark': {
        'normal':10,
        'fire':10,
        'water':10,
        'electric':10,
        'grass':10,
        'ice':10,
        'fighting':2.5,
        'poison':10,
        'ground':10,
        'flying':10,
        'psychic':20,
        'bug':10,
        'rock':10,
        'ghost':20,
        'dragon':10,
        'dark':2.5,
        'steel':10,
        'fairy':2.5,
    },
    'steel': {
        'normal':10,
        'fire':2.5,
        'water':2.5,
        'electric':2.5,
        'grass':10,
        'ice':20,
        'fighting':10,
        'poison':10,
        'ground':10,
        'flying':10,
        'psychic':10,
        'bug':10,
        'rock':20,
        'ghost':10,
        'dragon':10,
        'dark':10,
        'steel':2.5,
        'fairy':20,
    },
    'fairy': {
        'normal':10,
        'fire':2.5,
        'water':10,
        'electric':10,
        'grass':10,
        'ice':10,
        'fighting':20,
        'poison':2.5,
        'ground':10,
        'flying':10,
        'psychic':10,
        'bug':10,
        'rock':10,
        'ghost':10,
        'dragon':10,
        'dark':20,
        'steel':20,
        'fairy':2.5,
    },
}

item_url = {
    'master-ball': 'http://pokeapi.co/api/v2/item/1',
    'ultra-ball': 'http://pokeapi.co/api/v2/item/2',
    'great-ball': 'http://pokeapi.co/api/v2/item/3',
    'poke-ball': 'http://pokeapi.co/api/v2/item/4',
    'safari-ball': 'http://pokeapi.co/api/v2/item/5',
    'net-ball': 'http://pokeapi.co/api/v2/item/6',
    'dive-ball': 'http://pokeapi.co/api/v2/item/7',
    'nest-ball': 'http://pokeapi.co/api/v2/item/8',
    'repeat-ball': 'http://pokeapi.co/api/v2/item/9',
    'timer-ball': 'http://pokeapi.co/api/v2/item/10',
    'luxury-ball': 'http://pokeapi.co/api/v2/item/11',
    'premier-ball': 'http://pokeapi.co/api/v2/item/12',
    'dusk-ball': 'http://pokeapi.co/api/v2/item/13',
    'heal-ball': 'http://pokeapi.co/api/v2/item/14',
    'quick-ball': 'http://pokeapi.co/api/v2/item/15',
    'cherish-ball': 'http://pokeapi.co/api/v2/item/16',
    'potion': 'http://pokeapi.co/api/v2/item/17',
    'antidote': 'http://pokeapi.co/api/v2/item/18',
    'burn-heal': 'http://pokeapi.co/api/v2/item/19',
    'ice-heal': 'http://pokeapi.co/api/v2/item/20',
    'awakening': 'http://pokeapi.co/api/v2/item/21',
    'paralyze-heal': 'http://pokeapi.co/api/v2/item/22',
    'full-restore': 'http://pokeapi.co/api/v2/item/23',
    'max-potion': 'http://pokeapi.co/api/v2/item/24',
    'hyper-potion': 'http://pokeapi.co/api/v2/item/25',
    'super-potion': 'http://pokeapi.co/api/v2/item/26',
    'full-heal': 'http://pokeapi.co/api/v2/item/27',
    'revive': 'http://pokeapi.co/api/v2/item/28',
    'max-revive': 'http://pokeapi.co/api/v2/item/29',
    'fresh-water': 'http://pokeapi.co/api/v2/item/30',
    'soda-pop': 'http://pokeapi.co/api/v2/item/31',
    'lemonade': 'http://pokeapi.co/api/v2/item/32',
    'moomoo-milk': 'http://pokeapi.co/api/v2/item/33',
    'energy-powder': 'http://pokeapi.co/api/v2/item/34',
    'energy-root': 'http://pokeapi.co/api/v2/item/35',
    'heal-powder': 'http://pokeapi.co/api/v2/item/36',
    'revival-herb': 'http://pokeapi.co/api/v2/item/37',
    'ether': 'http://pokeapi.co/api/v2/item/38',
    'max-ether': 'http://pokeapi.co/api/v2/item/39',
    'elixir': 'http://pokeapi.co/api/v2/item/40',
    'max-elixir': 'http://pokeapi.co/api/v2/item/41',
    'lava-cookie': 'http://pokeapi.co/api/v2/item/42',
    'berry-juice': 'http://pokeapi.co/api/v2/item/43',
    'sacred-ash': 'http://pokeapi.co/api/v2/item/44',
    'hp-up': 'http://pokeapi.co/api/v2/item/45',
    'protein': 'http://pokeapi.co/api/v2/item/46',
    'iron': 'http://pokeapi.co/api/v2/item/47',
    'carbos': 'http://pokeapi.co/api/v2/item/48',
    'calcium': 'http://pokeapi.co/api/v2/item/49',
    'rare-candy': 'http://pokeapi.co/api/v2/item/50',
}